defaults: &defaults
  adapter: mysql2
  encoding: utf8
  pool: 5

development: &development
  <<: *defaults
  database: rails
  username: rails
  password: rails
  socket: /tmp/mysql.sock

production: 
  <<: *defaults
  database: rails
  username: rails
  password: ja4jhjrqOo
  socket: /tmp/mysql.sock
